default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: shop_trololo_development

test:
  <<: *default
  database: shop_trololo_test
  pool: 6

production:
  <<: *default
  database: shop_trololo_production
  username: shop_trololo
  password: <%= ENV["SHOP_TROLOLO_DATABASE_PASSWORD"] %>
